### ISSUE TITLE
[siva] add metadata to libraries and locations

### ISSUE THREAD

**Issue by jfontan** [src-d/go-borges#22]
Add a companion metadata file that describes the versions included in the siva files. The versions are numeric and consecutive and define a offset:

```yaml
---
versions:
    0:
        offset: 1234
        size: 1234
    1:
        offset: 4567
        size: 3333
```

Also add a metadata file to the library root to specify the last version ready.

* `library.yaml`:

```yaml
---
version: 2
```

This information will be use to open the repositories from that library in the latest version.
